// This file is generated by `pnpm run generate:config-types`. Do not edit.

import type { CliResolutionSource, CliTool, EngineKind, EventType, LabelSource, MessagingProviderKind, NotificationKind, SourceKind, UpdateMode } from "../types.generated";

export type WebhookTunnelMode = "quick" | "command" | "listener";
export const WEBHOOK_TUNNEL_MODES = ["quick","command","listener"] as const;

export type RemoteCapability = "terminal" | "local-api" | "messaging";
export const REMOTE_CAPABILITIES = ["terminal","local-api","messaging"] as const;

export type SourcePolicyMode = "loopback" | "lan" | "custom";
export const SOURCE_POLICY_MODES = ["loopback","lan","custom"] as const;

export type RemoteTunnelMode = "quick" | "command" | "listener" | "lan";
export const REMOTE_TUNNEL_MODES = ["quick","command","listener","lan"] as const;

export type RemoteEntrypointState = "bound" | "bound-no-auth" | "error";
export const REMOTE_ENTRYPOINT_STATES = ["bound","bound-no-auth","error"] as const;

export type RemoteTunnelState = "running" | "stopped" | "error";
export const REMOTE_TUNNEL_STATES = ["running","stopped","error"] as const;

export type OutboxConfig = {
/**
 * Staleness TTL for a `notification` action (seconds). A `pending` notification whose
 * `created_at` is older than this is dead-lettered instead of executed. `0` DISABLES the TTL
 * (the action never expires) — a safe sentinel so a misconfigured `0` can't expire every
 * queued action instantly. The per-kind resolver in `outbox::service` (`ttl_secs`, an
 * exhaustive `match ActionKind`) is the Hard carrier forcing a new kind to declare its own TTL.
 */
notificationTtlSecs: number, };

export type RuleActionKind = "review" | "check" | "notify";
export const RULE_ACTION_KINDS = ["review","check","notify"] as const;

export type RuleActionDedupePolicy = "event" | "action";
export const RULE_ACTION_DEDUPE_POLICIES = ["event","action"] as const;

export type RuleActionTarget = { "kind": "none" } | { "kind": "notificationChannels", channelIds: Array<string>, } | { "kind": "messagingConversation", integrationId: string, conversationId: string, };

export type RuleActionConfig = { id: string, kind: RuleActionKind, enabled: boolean, target: RuleActionTarget, dedupePolicy: RuleActionDedupePolicy, delaySecs: number, level: string, };

export type ReviewLifecycleEvent = "started" | "completed" | "failed" | "interrupted";
export const REVIEW_LIFECYCLE_EVENTS = ["started","completed","failed","interrupted"] as const;

export type ReviewLifecycleTarget = { "kind": "notificationChannels", channelIds: Array<string>, } | { "kind": "messagingConversation", integrationId: string, conversationId: string, };

export type ReviewLifecycleNotificationConfig = { enabled: boolean, events: Array<ReviewLifecycleEvent>, targets: Array<ReviewLifecycleTarget>, startDelaySecs: number, endDelaySecs: number, };
export const DEFAULT_REVIEW_LIFECYCLE_NOTIFICATION_CONFIG: ReviewLifecycleNotificationConfig = {"enabled":false,"events":["started","completed","failed","interrupted"],"targets":[{"kind":"notificationChannels","channelIds":[]}],"startDelaySecs":0,"endDelaySecs":0};

export type RuleConfig = { id: string, name: string, enabled: boolean, source: SourceKind | null, eventType: EventType | null, projectId: string, repo: string, labelsAny: Array<string>, labelsAll: Array<string>, titleContains: string, bodyContains: string, actions: Array<RuleActionConfig>, allowActionKinds: Array<RuleActionKind>, denyActionKinds: Array<RuleActionKind>, };

export type NotificationChannel = { id: string, name: string, kind: NotificationKind, enabled: boolean, webhookUrl: string, webhookSecret: string, telegramBotToken: string, telegramChatId: string, smtpHost: string, smtpPort: number, smtpUsername: string, smtpPassword: string, smtpFrom: string, smtpTo: string, timeoutSecs: number, };

export type NotificationSettings = { channels: Array<NotificationChannel>, };
export const DEFAULT_NOTIFICATION_SETTINGS: NotificationSettings = {"channels":[{"id":"desktop","name":"Desktop","kind":"desktop","enabled":true,"webhookUrl":"","webhookSecret":"","telegramBotToken":"","telegramChatId":"","smtpHost":"","smtpPort":587,"smtpUsername":"","smtpPassword":"","smtpFrom":"","smtpTo":"","timeoutSecs":15}]};

export type MessagingIntegration = { id: string, name: string, kind: MessagingProviderKind, enabled: boolean, verificationToken: string, encryptKey: string, appId: string, appSecret: string, botOpenId: string,
/**
 * Stable provider conversation ids allowed to execute commands. Empty fail-closes when enabled.
 */
allowedConversationIds: Array<string>,
/**
 * Whether group chat events must mention the bot before command parsing.
 */
requireMention: boolean, timeoutSecs: number, };
export const DEFAULT_MESSAGING_INTEGRATION: MessagingIntegration = {"id":"","name":"飞书","kind":"feishu","enabled":false,"verificationToken":"","encryptKey":"","appId":"","appSecret":"","botOpenId":"","allowedConversationIds":[],"requireMention":true,"timeoutSecs":15};

export type MessagingSettings = { integrations: Array<MessagingIntegration>, };
export const DEFAULT_MESSAGING_SETTINGS: MessagingSettings = {"integrations":[]};

export type SourcePolicy = { mode: SourcePolicyMode, allow: Array<string>, };

export type RemoteRoute = { id: string, name: string, path: string, capability: RemoteCapability, enabled: boolean, authToken: string, terminalRead: boolean, terminalWrite: boolean, terminalCreate: boolean, terminalAdmin: boolean, };

export type RemoteEntrypoint = { id: string, name: string, bindHost: string, port: number, enabled: boolean, sourcePolicy: SourcePolicy, allowedOrigins: Array<string>, trustedProxies: Array<string>, routes: Array<RemoteRoute>, };

export type RemoteTunnel = { id: string, name: string, mode: RemoteTunnelMode, targetEntrypointId: string, bindHost: string, port: number, command: string, publicUrl: string, enabled: boolean, };

export type RemoteAccessConfig = { entrypoints: Array<RemoteEntrypoint>, tunnels: Array<RemoteTunnel>, };

export type CliPath = string;

export type CliToolsConfig = { ghPath: CliPath, azPath: CliPath, codexPath: CliPath, claudePath: CliPath, cloudflaredPath: CliPath, };
export const DEFAULT_CLI_TOOLS_CONFIG: CliToolsConfig = {"ghPath":"","azPath":"","codexPath":"","claudePath":"","cloudflaredPath":""};

export type CliToolProbeStatus = { tool: CliTool, configuredPath: string, resolvedPath: string | null, source: CliResolutionSource | null, available: boolean, pendingRestart: boolean, message: string, };

export type Project = {
/**
 * Stable identifier (the migration assigns `"default"` to the lifted
 * single-project config; new projects get a fresh id). Used as the routing
 * key on every PR/review event and by [`super::service::project`] lookup.
 */
id: string,
/**
 * Human-readable label shown in the project switcher.
 */
name: string,
/**
 * Whether this project is polled/reviewed. Disabled projects are skipped by
 * `validate` (their fields are not checked) and by the scheduler.
 */
enabled: boolean,
/**
 * Monitored repo. Shape is source-dependent: `owner/name` for
 * [`SourceKind::Github`]; a bare repository name/slug for [`SourceKind::Azure`]
 * (org/project come from `azure_org`/`azure_project`) and [`SourceKind::Bitbucket`]
 * (project key comes from `bitbucket_project`). Validated per-source in `validate_project`.
 */
repo: string,
/**
 * Absolute path to the local clone codex runs the pr-review skill against.
 */
repoRoot: string,
/**
 * Scheduled-pull period in seconds.
 */
pollIntervalSecs: number,
/**
 * PR author allowlist (mirrors the dispatcher's author gate).
 */
authors: Array<string>,
/**
 * Path (relative to `repo_root`) of the codex pr-review skill to invoke.
 */
skillRelPath: string,
/**
 * Per-PR cooldown between dispatches of the same `(pr, kind)`.
 */
prCooldownSeconds: number,
/**
 * Which PR source backs the monitor: [`SourceKind::Github`] (`gh` CLI),
 * [`SourceKind::Azure`] (`az` CLI), or [`SourceKind::Bitbucket`] (REST). #11
 * reservation: future variant gates GitLab.
 */
sourceKind: SourceKind,
/**
 * Which review engine runs against a PR. #11 reservation: today only
 * [`EngineKind::Codex`]; future variant gates Claude.
 */
engineKind: EngineKind,
/**
 * 手填的 codex 模型名（仅 [`EngineKind::Codex`] 用）。非空时作为 `turn/start` 的
 * `model` 覆盖（codex app-server 是单进程，模型只能 per-turn 选）；留空=codex 默认。
 * 自由文本不校验（模型列表多变）。
 */
codexModel: string,
/**
 * 手填的 claude 模型名（仅 [`EngineKind::Claude`] 用）。非空时作为 `claude -p` 的
 * `--model` 参数；留空=claude CLI 默认。自由文本不校验。
 */
claudeModel: string,
/**
 * 本项目 PR 列表的更新模式（#818）。默认 [`UpdateMode::WebhookOnly`]：**启动不自动
 * 轮询 CLI**，列表仅由 webhook 推送更新。`pull-only`/`hybrid` 才起周期轮询；`manual`
 * 只在「立即拉取」时跑一次性发现。调度器据此 gate 是否为本项目起轮询 loop。
 */
updateMode: UpdateMode,
/**
 * Azure DevOps 组织名（#818，仅 [`SourceKind::Azure`] 用）。`az repos pr list
 * --organization https://dev.azure.com/<org>` 的 `<org>`。GitHub 源留空。
 */
azureOrg: string,
/**
 * Azure DevOps 项目名（#818，仅 [`SourceKind::Azure`] 用）。`az repos pr list
 * --project <project>` 的 `<project>`。GitHub 源留空。
 */
azureProject: string,
/**
 * 标签来源（AB#717）：`native`=用来源方自带的 PR 标签；`title`=从 PR 标题的方括号
 * 片段解析（如 `[pr-status/need-fix]`）。默认 [`LabelSource::Native`]（向后兼容）。
 * Bitbucket Server 无原生 PR 标签，故 [`SourceKind::Bitbucket`] 项目**必须**用
 * [`LabelSource::Title`]（由 [`validate_project`] 强制）。
 */
labelSource: LabelSource,
/**
 * Bitbucket Server/DC 基址（AB#717，仅 [`SourceKind::Bitbucket`] 用），如
 * `https://bitbucket.mycompany.com`。被插值进 REST URL，故须 URL 安全。其余源留空。
 */
bitbucketHost: string,
/**
 * Bitbucket 项目 key（AB#717，仅 [`SourceKind::Bitbucket`] 用），如 `GOCELL`；个人
 * 仓库用 `~username`。REST 路径段 `.../projects/{project}/repos/{repo}/...`。其余源留空。
 */
bitbucketProject: string,
/**
 * Bitbucket HTTP access token（PAT，AB#717，仅 [`SourceKind::Bitbucket`] 用），用作
 * `Authorization: Bearer <token>`。无 CLI 登录，故凭据存配置。其余源留空。
 */
bitbucketToken: string, };

export type AppConfig = {
/**
 * Monitored projects. Empty on first launch (onboarding then adds the first).
 */
projects: Array<Project>,
/**
 * `id` of the project the UI currently focuses. Empty when `projects` is empty.
 */
activeProjectId: string,
/**
 * 是否启用 webhook 接收端（#9）。开关本身只 gate「能否启动」本地接收端 + Cloudflare
 * 隧道（手动 `start_webhook` 命令）——不自动起、不影响轮询路径。
 */
webhookEnabled: boolean,
/**
 * webhook 本地 HTTP 监听端口（仅绑 127.0.0.1；公网经 cloudflared 隧道代理到此）。
 */
webhookPort: number,
/**
 * GitHub webhook 的 HMAC secret（`X-Hub-Signature-256` 验签）。`webhook_enabled`
 * 时必填——公网端点没有验签即可被任意 POST 伪造触发 review。
 */
webhookSecret: string,
/**
 * Managed third-party executable paths. Empty fields use deterministic discovery.
 */
cliTools: CliToolsConfig,
/**
 * 隧道暴露模式（#9）。`quick`=Cloudflare Quick Tunnel（默认，现状）；
 * `command`=自定义隧道命令（见 `webhook_tunnel_command`）；`listener`=只监听本地端口、
 * 隧道完全外置。接收端只管 bind/验签/派发，隧道如何暴露公网由本字段分支。
 */
webhookTunnelMode: WebhookTunnelMode,
/**
 * `command` 模式下拉起的自定义隧道命令（按空白分词；首 token 为程序、其余为参数；
 * 字面量 `{port}` 替换成实际监听端口）。**直接 exec、不过 shell**（防注入）。仅
 * `command` 模式必填（由 `validate` 强制）；其他模式留空。
 */
webhookTunnelCommand: string,
/**
 * `command` / `listener` 模式下手填的公网 URL 根（隧道由外部暴露，接收端无从抓取）。
 * 非空则作为 `WebhookStatus.public_url`，UI 据此拼出 GitHub Payload URL；为空则 `None`。
 * `quick` 模式忽略本字段（URL 从 cloudflared 日志抓取）。
 */
webhookPublicUrl: string,
/**
 * 本地 REST API 的 Bearer token（AB#1043）。**空 = fail-closed 禁用**：entrypoint 仍绑定，但
 * handler 每个请求实时读取本字段做常量时间比较，空 token 一律 401。设 / 清即时生效、无需
 * 重启。loopback-only 仍是触发端点（本机任意进程 + DNS rebinding 可达），故非空时按
 * `LOCAL_API_TOKEN_MIN_LEN` 强制最小长度（与 `webhook_secret` 同理由）。
 */
localApiToken: string,
/**
 * Outbox worker policy (AB#1182): per-kind staleness TTLs for the durable action queue. Global
 * (one policy serves every project). Forward-compat via the nested `#[serde(default)]`.
 */
outbox: OutboxConfig,
/**
 * Configurable Event → Action rules (#1371). This replaces the old per-project
 * `reviewLabel` / `checkLabel` / `autoReview` runtime path; old persisted fields are
 * migrated into rules on load.
 */
rules: Array<RuleConfig>,
/**
 * Outbound notification channels (AB#1459). Forward-compatible default seeds a local desktop
 * channel; external channels are user-added/disabled until configured.
 */
notifications: NotificationSettings,
/**
 * Bidirectional messaging/bot integrations (#1559). Separate from outbound notifications.
 */
messaging: MessagingSettings,
/**
 * Review lifecycle notifications. Routes review started / terminal events to notification
 * channels or messaging conversations through the durable outbox.
 */
reviewLifecycleNotifications: ReviewLifecycleNotificationConfig,
/**
 * Declarative Remote Access entrypoints and tunnels. This is the single runtime source:
 * each entrypoint owns one bound port and mounts one or more capability routes.
 */
remoteAccess: RemoteAccessConfig, };

export type RemoteRouteRuntimeStatus = { id: string, path: string, capability: RemoteCapability, enabled: boolean, };

export type RemoteEntrypointRuntimeStatus = { id: string, bound: boolean, boundPort?: number, state: RemoteEntrypointState, message: string, routes: Array<RemoteRouteRuntimeStatus>, };

export type RemoteTunnelRuntimeStatus = { id: string, mode: RemoteTunnelMode, targetEntrypointId: string, state: RemoteTunnelState, publicUrl?: string, message: string, logs: Array<string>, };

export type RemoteAccessRuntimeStatus = { entrypoints: Array<RemoteEntrypointRuntimeStatus>, tunnels: Array<RemoteTunnelRuntimeStatus>, };
