//! Test-only Rust -> TypeScript wire contract generator.

use std::{
    fs,
    path::{Path, PathBuf},
};

use serde::Serialize;
use strum::IntoEnumIterator;
use ts_rs::{Config, TS};

use crate::{
    config::model::{
        AppConfig, Listener, ListenerAuthMode, ListenerKind, OutboxConfig, Project, Tunnel,
    },
    model::{EngineKind, LabelSource, SourceKind, UpdateMode, WebhookTunnelMode},
    remote::status::{ListenerRuntimeStatus, ListenerState},
};

const HEADER: &str =
    "// This file is generated by `pnpm run generate:config-types`. Do not edit.\n\n";

fn config() -> Config {
    Config::new().with_large_int("number")
}

fn declaration<T: TS>(cfg: &Config) -> String {
    format!("export {}\n", T::decl(cfg))
}

fn enum_values<T>() -> String
where
    T: IntoEnumIterator + Serialize,
{
    let values = T::iter()
        .map(|value| {
            serde_json::to_value(value)
                .expect("enum serializes")
                .as_str()
                .expect("enum serializes to a string")
                .to_string()
        })
        .collect::<Vec<_>>();
    serde_json::to_string(&values).expect("enum values serialize")
}

fn option_array<T>(name: &str) -> String
where
    T: IntoEnumIterator + Serialize,
{
    format!("export const {name} = {} as const;\n", enum_values::<T>())
}

fn write_if_changed(path: &Path, contents: &str) {
    if fs::read_to_string(path).ok().as_deref() == Some(contents) {
        return;
    }
    fs::write(path, contents).expect("write generated TypeScript");
}

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("src-tauri has a parent directory")
        .to_path_buf()
}

fn generated_outputs() -> Vec<(&'static str, String)> {
    let cfg = config();
    let mut shared = String::from(HEADER);
    shared.push_str(&declaration::<SourceKind>(&cfg));
    shared.push_str(&option_array::<SourceKind>("SOURCE_KINDS"));
    shared.push('\n');
    shared.push_str(&declaration::<EngineKind>(&cfg));
    shared.push_str(&option_array::<EngineKind>("ENGINE_KINDS"));
    shared.push('\n');
    shared.push_str(&declaration::<LabelSource>(&cfg));
    shared.push_str(&option_array::<LabelSource>("LABEL_SOURCES"));
    shared.push('\n');
    shared.push_str(&declaration::<UpdateMode>(&cfg));
    shared.push_str(&option_array::<UpdateMode>("UPDATE_MODES"));

    let mut config_types = String::from(HEADER);
    config_types.push_str(
        "import type { EngineKind, LabelSource, SourceKind, UpdateMode } from \"../types.generated\";\n\n",
    );
    config_types.push_str(&declaration::<WebhookTunnelMode>(&cfg));
    config_types.push_str(&option_array::<WebhookTunnelMode>("WEBHOOK_TUNNEL_MODES"));
    config_types.push('\n');
    config_types.push_str(&declaration::<ListenerKind>(&cfg));
    config_types.push_str(&option_array::<ListenerKind>("LISTENER_KINDS"));
    config_types.push('\n');
    config_types.push_str(&declaration::<ListenerState>(&cfg));
    config_types.push_str(&option_array::<ListenerState>("LISTENER_STATES"));
    config_types.push('\n');
    config_types.push_str(&declaration::<ListenerAuthMode>(&cfg));
    config_types.push_str(&option_array::<ListenerAuthMode>("LISTENER_AUTH_MODES"));
    config_types.push('\n');
    config_types.push_str(&declaration::<OutboxConfig>(&cfg));
    config_types.push('\n');
    config_types.push_str(&declaration::<Listener>(&cfg));
    config_types.push('\n');
    config_types.push_str(&declaration::<Tunnel>(&cfg));
    config_types.push('\n');
    config_types.push_str(&declaration::<Project>(&cfg));
    config_types.push('\n');
    config_types.push_str(&declaration::<AppConfig>(&cfg));
    config_types.push('\n');
    config_types.push_str(&declaration::<ListenerRuntimeStatus>(&cfg));

    vec![
        ("src/types.generated.ts", shared),
        ("src/config/types.generated.ts", config_types),
    ]
}

#[test]
fn generated_config_types_are_current() {
    let repo_root = repo_root();
    for (relative_path, expected) in generated_outputs() {
        let path = repo_root.join(relative_path);
        let actual = fs::read_to_string(&path)
            .unwrap_or_else(|err| panic!("read generated TypeScript {}: {err}", path.display()));
        assert_eq!(
            actual, expected,
            "{} is out of date; run `pnpm run generate:config-types`",
            relative_path
        );
    }
}

#[test]
#[ignore = "writes generated TypeScript files; run via `pnpm run generate:config-types`"]
fn export_config_types() {
    let repo_root = repo_root();
    for (relative_path, contents) in generated_outputs() {
        write_if_changed(&repo_root.join(relative_path), &contents);
    }
}
