//! Test-only Rust -> TypeScript wire contract generator.

use std::{
    fs,
    path::{Path, PathBuf},
};

use serde::Serialize;
use strum::IntoEnumIterator;
use ts_rs::{Config, TS};

use crate::{
    config::model::{
        AppConfig, MessagingIntegration, MessagingSettings, NotificationChannel,
        NotificationSettings, OutboxConfig, Project, RemoteAccessConfig, RemoteCapability,
        RemoteEntrypoint, RemoteRoute, RemoteTunnel, RemoteTunnelMode,
        ReviewLifecycleNotificationConfig, ReviewLifecycleTarget, RuleActionConfig,
        RuleActionDedupePolicy, RuleActionKind, RuleActionTarget, RuleConfig, SourcePolicy,
        SourcePolicyMode,
    },
    model::{
        ActionStatus, EngineKind, EventType, LabelSource, MessagingEvent, MessagingEventEntry,
        MessagingEventStatus, MessagingIntegrationOption, MessagingProviderCapability,
        MessagingProviderKind, MessagingReplyAudit, NotificationKind, NotificationLevel,
        ReviewLifecycleEvent, SendMessagingRequest, SendMessagingResponse, SendNotificationRequest,
        SendNotificationResponse, SourceKind, UpdateMode, WebhookTunnelMode,
    },
    remote::status::{
        RemoteAccessRuntimeStatus, RemoteEntrypointRuntimeStatus, RemoteEntrypointState,
        RemoteRouteRuntimeStatus, RemoteTunnelRuntimeStatus, RemoteTunnelState,
    },
    rule::store::RuleMatchEntry,
};

const HEADER: &str =
    "// This file is generated by `pnpm run generate:config-types`. Do not edit.\n\n";

fn config() -> Config {
    Config::new().with_large_int("number")
}

fn declaration<T: TS>(cfg: &Config) -> String {
    let decl = T::decl(cfg)
        .lines()
        .map(str::trim_end)
        .collect::<Vec<_>>()
        .join("\n");
    format!("export {decl}\n")
}

fn enum_values<T>() -> String
where
    T: IntoEnumIterator + Serialize,
{
    let values = T::iter()
        .map(|value| {
            serde_json::to_value(value)
                .expect("enum serializes")
                .as_str()
                .expect("enum serializes to a string")
                .to_string()
        })
        .collect::<Vec<_>>();
    serde_json::to_string(&values).expect("enum values serialize")
}

fn option_array<T>(name: &str) -> String
where
    T: IntoEnumIterator + Serialize,
{
    format!("export const {name} = {} as const;\n", enum_values::<T>())
}

fn default_const<T: Serialize>(name: &str, type_name: &str, value: &T) -> String {
    format!(
        "export const {name}: {type_name} = {};\n",
        serde_json::to_string(value).expect("default value serializes")
    )
}

fn write_if_changed(path: &Path, contents: &str) {
    if fs::read_to_string(path).ok().as_deref() == Some(contents) {
        return;
    }
    fs::write(path, contents).expect("write generated TypeScript");
}

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("src-tauri has a parent directory")
        .to_path_buf()
}

fn generated_outputs() -> Vec<(&'static str, String)> {
    let cfg = config();
    let mut shared = String::from(HEADER);
    shared.push_str(&declaration::<SourceKind>(&cfg));
    shared.push_str(&option_array::<SourceKind>("SOURCE_KINDS"));
    shared.push('\n');
    shared.push_str(&declaration::<EngineKind>(&cfg));
    shared.push_str(&option_array::<EngineKind>("ENGINE_KINDS"));
    shared.push('\n');
    shared.push_str(&declaration::<LabelSource>(&cfg));
    shared.push_str(&option_array::<LabelSource>("LABEL_SOURCES"));
    shared.push('\n');
    shared.push_str(&declaration::<UpdateMode>(&cfg));
    shared.push_str(&option_array::<UpdateMode>("UPDATE_MODES"));
    shared.push('\n');
    shared.push_str(&declaration::<EventType>(&cfg));
    shared.push_str(&option_array::<EventType>("EVENT_TYPES"));
    shared.push('\n');
    shared.push_str(&declaration::<NotificationKind>(&cfg));
    shared.push_str(&option_array::<NotificationKind>("NOTIFICATION_KINDS"));
    shared.push('\n');
    shared.push_str(&declaration::<MessagingProviderKind>(&cfg));
    shared.push_str(&option_array::<MessagingProviderKind>(
        "MESSAGING_PROVIDER_KINDS",
    ));
    shared.push('\n');
    shared.push_str(&declaration::<MessagingEventStatus>(&cfg));
    shared.push_str(&option_array::<MessagingEventStatus>(
        "MESSAGING_EVENT_STATUSES",
    ));
    shared.push('\n');
    shared.push_str(&declaration::<ActionStatus>(&cfg));
    shared.push_str(&option_array::<ActionStatus>("ACTION_STATUSES"));
    shared.push('\n');
    shared.push_str(&declaration::<MessagingProviderCapability>(&cfg));
    shared.push('\n');
    shared.push_str(&declaration::<MessagingIntegrationOption>(&cfg));
    shared.push('\n');
    shared.push_str(&declaration::<MessagingEvent>(&cfg));
    shared.push('\n');
    shared.push_str(&declaration::<MessagingReplyAudit>(&cfg));
    shared.push('\n');
    shared.push_str(&declaration::<MessagingEventEntry>(&cfg));
    shared.push('\n');
    shared.push_str(&declaration::<NotificationLevel>(&cfg));
    shared.push_str(&option_array::<NotificationLevel>("NOTIFICATION_LEVELS"));
    shared.push('\n');
    shared.push_str(&declaration::<SendNotificationRequest>(&cfg));
    shared.push('\n');
    shared.push_str(&declaration::<SendNotificationResponse>(&cfg));
    shared.push('\n');
    shared.push_str(&declaration::<SendMessagingRequest>(&cfg));
    shared.push('\n');
    shared.push_str(&declaration::<SendMessagingResponse>(&cfg));
    shared.push('\n');
    shared.push_str(&declaration::<RuleMatchEntry>(&cfg));

    let mut config_types = String::from(HEADER);
    config_types.push_str(
        "import type { EngineKind, EventType, LabelSource, MessagingProviderKind, NotificationKind, SourceKind, UpdateMode } from \"../types.generated\";\n\n",
    );
    config_types.push_str(&declaration::<WebhookTunnelMode>(&cfg));
    config_types.push_str(&option_array::<WebhookTunnelMode>("WEBHOOK_TUNNEL_MODES"));
    config_types.push('\n');
    config_types.push_str(&declaration::<RemoteCapability>(&cfg));
    config_types.push_str(&option_array::<RemoteCapability>("REMOTE_CAPABILITIES"));
    config_types.push('\n');
    config_types.push_str(&declaration::<SourcePolicyMode>(&cfg));
    config_types.push_str(&option_array::<SourcePolicyMode>("SOURCE_POLICY_MODES"));
    config_types.push('\n');
    config_types.push_str(&declaration::<RemoteTunnelMode>(&cfg));
    config_types.push_str(&option_array::<RemoteTunnelMode>("REMOTE_TUNNEL_MODES"));
    config_types.push('\n');
    config_types.push_str(&declaration::<RemoteEntrypointState>(&cfg));
    config_types.push_str(&option_array::<RemoteEntrypointState>(
        "REMOTE_ENTRYPOINT_STATES",
    ));
    config_types.push('\n');
    config_types.push_str(&declaration::<RemoteTunnelState>(&cfg));
    config_types.push_str(&option_array::<RemoteTunnelState>("REMOTE_TUNNEL_STATES"));
    config_types.push('\n');
    config_types.push_str(&declaration::<OutboxConfig>(&cfg));
    config_types.push('\n');
    config_types.push_str(&declaration::<RuleActionKind>(&cfg));
    config_types.push_str(&option_array::<RuleActionKind>("RULE_ACTION_KINDS"));
    config_types.push('\n');
    config_types.push_str(&declaration::<RuleActionDedupePolicy>(&cfg));
    config_types.push_str(&option_array::<RuleActionDedupePolicy>(
        "RULE_ACTION_DEDUPE_POLICIES",
    ));
    config_types.push('\n');
    config_types.push_str(&declaration::<RuleActionTarget>(&cfg));
    config_types.push('\n');
    config_types.push_str(&declaration::<RuleActionConfig>(&cfg));
    config_types.push('\n');
    config_types.push_str(&declaration::<ReviewLifecycleEvent>(&cfg));
    config_types.push_str(&option_array::<ReviewLifecycleEvent>(
        "REVIEW_LIFECYCLE_EVENTS",
    ));
    config_types.push('\n');
    config_types.push_str(&declaration::<ReviewLifecycleTarget>(&cfg));
    config_types.push('\n');
    config_types.push_str(&declaration::<ReviewLifecycleNotificationConfig>(&cfg));
    config_types.push_str(&default_const(
        "DEFAULT_REVIEW_LIFECYCLE_NOTIFICATION_CONFIG",
        "ReviewLifecycleNotificationConfig",
        &ReviewLifecycleNotificationConfig::default(),
    ));
    config_types.push('\n');
    config_types.push_str(&declaration::<RuleConfig>(&cfg));
    config_types.push('\n');
    config_types.push_str(&declaration::<NotificationChannel>(&cfg));
    config_types.push('\n');
    config_types.push_str(&declaration::<NotificationSettings>(&cfg));
    config_types.push_str(&default_const(
        "DEFAULT_NOTIFICATION_SETTINGS",
        "NotificationSettings",
        &NotificationSettings::default(),
    ));
    config_types.push('\n');
    config_types.push_str(&declaration::<MessagingIntegration>(&cfg));
    config_types.push_str(&default_const(
        "DEFAULT_MESSAGING_INTEGRATION",
        "MessagingIntegration",
        &MessagingIntegration::default(),
    ));
    config_types.push('\n');
    config_types.push_str(&declaration::<MessagingSettings>(&cfg));
    config_types.push_str(&default_const(
        "DEFAULT_MESSAGING_SETTINGS",
        "MessagingSettings",
        &MessagingSettings::default(),
    ));
    config_types.push('\n');
    config_types.push_str(&declaration::<SourcePolicy>(&cfg));
    config_types.push('\n');
    config_types.push_str(&declaration::<RemoteRoute>(&cfg));
    config_types.push('\n');
    config_types.push_str(&declaration::<RemoteEntrypoint>(&cfg));
    config_types.push('\n');
    config_types.push_str(&declaration::<RemoteTunnel>(&cfg));
    config_types.push('\n');
    config_types.push_str(&declaration::<RemoteAccessConfig>(&cfg));
    config_types.push('\n');
    config_types.push_str(&declaration::<Project>(&cfg));
    config_types.push('\n');
    config_types.push_str(&declaration::<AppConfig>(&cfg));
    config_types.push('\n');
    config_types.push_str(&declaration::<RemoteRouteRuntimeStatus>(&cfg));
    config_types.push('\n');
    config_types.push_str(&declaration::<RemoteEntrypointRuntimeStatus>(&cfg));
    config_types.push('\n');
    config_types.push_str(&declaration::<RemoteTunnelRuntimeStatus>(&cfg));
    config_types.push('\n');
    config_types.push_str(&declaration::<RemoteAccessRuntimeStatus>(&cfg));

    vec![
        ("src/types.generated.ts", shared),
        ("src/config/types.generated.ts", config_types),
    ]
}

#[test]
fn generated_config_types_are_current() {
    let repo_root = repo_root();
    for (relative_path, expected) in generated_outputs() {
        let path = repo_root.join(relative_path);
        let actual = fs::read_to_string(&path)
            .unwrap_or_else(|err| panic!("read generated TypeScript {}: {err}", path.display()));
        assert_eq!(
            actual, expected,
            "{} is out of date; run `pnpm run generate:config-types`",
            relative_path
        );
    }
}

#[test]
#[ignore = "writes generated TypeScript files; run via `pnpm run generate:config-types`"]
fn export_config_types() {
    let repo_root = repo_root();
    for (relative_path, contents) in generated_outputs() {
        write_if_changed(&repo_root.join(relative_path), &contents);
    }
}
