//! Test-only Rust -> TypeScript wire contract generator.

use std::{
    fs,
    path::{Path, PathBuf},
};

use serde::Serialize;
use strum::IntoEnumIterator;
use ts_rs::{Config, TS};

use crate::{
    config::model::{
        AppConfig, CliPath, CliToolProbeStatus, CliToolsConfig, MessagingIntegration,
        MessagingSettings, NotificationChannel, NotificationSettings, OutboxConfig, Project,
        RemoteAccessConfig, RemoteCapability, RemoteEntrypoint, RemoteRoute, RemoteTunnel,
        RemoteTunnelMode, ReviewLifecycleNotificationConfig, ReviewLifecycleTarget,
        RuleActionConfig, RuleActionDedupePolicy, RuleActionKind, RuleActionTarget, RuleConfig,
        SourcePolicy, SourcePolicyMode,
    },
    model::{
        ActionStatus, ClaudeEffort, CliResolutionSource, CliTool, CodexReasoningEffort, EngineKind,
        EventEnvelope, EventPayload, EventSubject, EventType, ExternalRequestId,
        ExternalTriggerOrigin, InboxDedupeKey, InboxEventId, LabelSource, MessagingCardTemplate,
        MessagingConnectionState, MessagingConnectionStatus, MessagingEvent, MessagingEventEntry,
        MessagingEventStatus, MessagingIntegrationOption, MessagingProviderCapability,
        MessagingProviderKind, MessagingReplyAudit, MessagingSendContent, NotificationKind,
        NotificationLevel, OutboxProducerKey, PullRequestView, ReviewActionKey,
        ReviewLifecycleEvent, ReviewReceiptId, ReviewReceiptSnapshot, ReviewReceiptStatus,
        SendMessagingRequest, SendMessagingResponse, SendNotificationRequest,
        SendNotificationResponse, SourceKind, UpdateMode, WebhookTunnelMode,
    },
    remote::status::{
        RemoteAccessRuntimeStatus, RemoteEntrypointRuntimeStatus, RemoteEntrypointState,
        RemoteRouteRuntimeStatus, RemoteTunnelRuntimeStatus, RemoteTunnelState,
    },
    rule::store::RuleMatchEntry,
};

const HEADER: &str =
    "// This file is generated by `pnpm run generate:config-types`. Do not edit.\n\n";

fn config() -> Config {
    Config::new().with_large_int("number")
}

fn declaration<T: TS>(cfg: &Config) -> String {
    let decl = T::decl(cfg)
        .lines()
        .map(str::trim_end)
        .collect::<Vec<_>>()
        .join("\n");
    format!("export {decl}\n")
}

fn branded_declaration<T: TS>(
    cfg: &Config,
    primitive: &str,
    constructor: &str,
    validation: &str,
) -> String {
    let name = T::name(cfg);
    format!(
        "export type {name} = Brand<{primitive}, \"{name}\">;\nexport function {constructor}(value: {primitive}): {name} {{\n  {validation}\n  return value as {name};\n}}\n"
    )
}

fn enum_values<T>() -> String
where
    T: IntoEnumIterator + Serialize,
{
    let values = T::iter()
        .map(|value| {
            serde_json::to_value(value)
                .expect("enum serializes")
                .as_str()
                .expect("enum serializes to a string")
                .to_string()
        })
        .collect::<Vec<_>>();
    serde_json::to_string(&values).expect("enum values serialize")
}

fn option_array<T>(name: &str) -> String
where
    T: IntoEnumIterator + Serialize,
{
    format!("export const {name} = {} as const;\n", enum_values::<T>())
}

fn messaging_long_connection_kinds_const() -> String {
    use crate::messaging::service::supports_long_connection;
    let kinds = MessagingProviderKind::iter()
        .filter(|kind| supports_long_connection(*kind))
        .map(MessagingProviderKind::as_wire)
        .collect::<Vec<_>>();
    format!(
        "export const MESSAGING_LONG_CONNECTION_KINDS = {} as const;\n",
        serde_json::to_string(&kinds).expect("long-connection kinds serialize")
    )
}

fn default_const<T: Serialize>(name: &str, type_name: &str, value: &T) -> String {
    format!(
        "export const {name}: {type_name} = {};\n",
        serde_json::to_string(value).expect("default value serializes")
    )
}

fn write_if_changed(path: &Path, contents: &str) {
    if fs::read_to_string(path).ok().as_deref() == Some(contents) {
        return;
    }
    fs::write(path, contents).expect("write generated TypeScript");
}

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("src-tauri has a parent directory")
        .to_path_buf()
}

fn generated_outputs() -> Vec<(&'static str, String)> {
    let cfg = config();
    let mut shared = String::from(HEADER);
    shared.push_str(&declaration::<CliTool>(&cfg));
    shared.push_str(&option_array::<CliTool>("CLI_TOOLS"));
    shared.push('\n');
    shared.push_str(&declaration::<CliResolutionSource>(&cfg));
    shared.push_str(&option_array::<CliResolutionSource>(
        "CLI_RESOLUTION_SOURCES",
    ));
    shared.push('\n');
    shared.push_str(&declaration::<SourceKind>(&cfg));
    shared.push_str(&option_array::<SourceKind>("SOURCE_KINDS"));
    shared.push('\n');
    shared.push_str(&declaration::<EngineKind>(&cfg));
    shared.push_str(&option_array::<EngineKind>("ENGINE_KINDS"));
    shared.push('\n');
    shared.push_str(&declaration::<CodexReasoningEffort>(&cfg));
    shared.push_str(&option_array::<CodexReasoningEffort>(
        "CODEX_REASONING_EFFORTS",
    ));
    shared.push('\n');
    shared.push_str(&declaration::<ClaudeEffort>(&cfg));
    shared.push_str(&option_array::<ClaudeEffort>("CLAUDE_EFFORTS"));
    shared.push('\n');
    shared.push_str(&declaration::<LabelSource>(&cfg));
    shared.push_str(&option_array::<LabelSource>("LABEL_SOURCES"));
    shared.push('\n');
    shared.push_str(&declaration::<UpdateMode>(&cfg));
    shared.push_str(&option_array::<UpdateMode>("UPDATE_MODES"));
    shared.push('\n');
    shared.push_str(&declaration::<EventType>(&cfg));
    shared.push_str(&option_array::<EventType>("EVENT_TYPES"));
    shared.push('\n');
    shared.push_str(&declaration::<PullRequestView>(&cfg));
    shared.push('\n');
    shared.push_str(&declaration::<ExternalTriggerOrigin>(&cfg));
    shared.push_str(&option_array::<ExternalTriggerOrigin>(
        "EXTERNAL_TRIGGER_ORIGINS",
    ));
    shared.push('\n');
    shared.push_str("declare const __brand: unique symbol;\n");
    shared.push_str(
        "export type Brand<T, Name extends string> = T & { readonly [__brand]: Name };\n",
    );
    shared.push_str(&branded_declaration::<ExternalRequestId>(
        &cfg,
        "string",
        "externalRequestId",
        &format!(
            "if (!/^[0-9a-f]{{{}}}$/.test(value)) throw new Error(\"requestId must be exactly {} lowercase hexadecimal characters\");",
            ExternalRequestId::LENGTH,
            ExternalRequestId::LENGTH
        ),
    ));
    for declaration in [
        branded_declaration::<InboxDedupeKey>(
            &cfg,
            "string",
            "inboxDedupeKey",
            "if (value.trim().length === 0) throw new Error(\"inbox dedupe key must not be empty\");",
        ),
        branded_declaration::<ReviewActionKey>(
            &cfg,
            "string",
            "reviewActionKey",
            "if (value.trim().length === 0) throw new Error(\"review action key must not be empty\");",
        ),
        branded_declaration::<OutboxProducerKey>(
            &cfg,
            "string",
            "outboxProducerKey",
            "if (value.trim().length === 0) throw new Error(\"outbox producer key must not be empty\");",
        ),
        branded_declaration::<InboxEventId>(
            &cfg,
            "number",
            "inboxEventId",
            "if (!Number.isSafeInteger(value) || value <= 0) throw new Error(\"inbox event id must be a positive safe integer\");",
        ),
        branded_declaration::<ReviewReceiptId>(
            &cfg,
            "number",
            "reviewReceiptId",
            "if (!Number.isSafeInteger(value) || value <= 0) throw new Error(\"review receipt id must be a positive safe integer\");",
        ),
    ] {
        shared.push_str(&declaration);
    }
    shared.push_str(&declaration::<ReviewReceiptStatus>(&cfg));
    shared.push_str(&option_array::<ReviewReceiptStatus>(
        "REVIEW_RECEIPT_STATUSES",
    ));
    shared.push_str(&declaration::<ReviewReceiptSnapshot>(&cfg));
    shared.push_str(&declaration::<EventSubject>(&cfg));
    shared.push_str(&declaration::<EventPayload>(&cfg));
    shared.push_str(&declaration::<EventEnvelope>(&cfg));
    shared.push('\n');
    shared.push_str(&declaration::<NotificationKind>(&cfg));
    shared.push_str(&option_array::<NotificationKind>("NOTIFICATION_KINDS"));
    shared.push('\n');
    shared.push_str(&declaration::<MessagingProviderKind>(&cfg));
    shared.push_str(&option_array::<MessagingProviderKind>(
        "MESSAGING_PROVIDER_KINDS",
    ));
    shared.push_str(&messaging_long_connection_kinds_const());
    shared.push('\n');
    shared.push_str(&declaration::<MessagingEventStatus>(&cfg));
    shared.push_str(&option_array::<MessagingEventStatus>(
        "MESSAGING_EVENT_STATUSES",
    ));
    shared.push('\n');
    shared.push_str(&declaration::<ActionStatus>(&cfg));
    shared.push_str(&option_array::<ActionStatus>("ACTION_STATUSES"));
    shared.push('\n');
    shared.push_str(&declaration::<MessagingProviderCapability>(&cfg));
    shared.push('\n');
    shared.push_str(&declaration::<MessagingIntegrationOption>(&cfg));
    shared.push('\n');
    shared.push_str(&declaration::<MessagingConnectionState>(&cfg));
    shared.push_str(&option_array::<MessagingConnectionState>(
        "MESSAGING_CONNECTION_STATES",
    ));
    shared.push('\n');
    shared.push_str(&declaration::<MessagingConnectionStatus>(&cfg));
    shared.push('\n');
    shared.push_str(&declaration::<MessagingEvent>(&cfg));
    shared.push('\n');
    shared.push_str(&declaration::<MessagingReplyAudit>(&cfg));
    shared.push('\n');
    shared.push_str(&declaration::<MessagingEventEntry>(&cfg));
    shared.push('\n');
    shared.push_str(&declaration::<NotificationLevel>(&cfg));
    shared.push_str(&option_array::<NotificationLevel>("NOTIFICATION_LEVELS"));
    shared.push('\n');
    shared.push_str(&declaration::<SendNotificationRequest>(&cfg));
    shared.push('\n');
    shared.push_str(&declaration::<SendNotificationResponse>(&cfg));
    shared.push('\n');
    shared.push_str(&declaration::<MessagingCardTemplate>(&cfg));
    shared.push_str(&option_array::<MessagingCardTemplate>(
        "MESSAGING_CARD_TEMPLATES",
    ));
    shared.push('\n');
    shared.push_str(&declaration::<MessagingSendContent>(&cfg));
    shared.push('\n');
    shared.push_str(&declaration::<SendMessagingRequest>(&cfg));
    shared.push('\n');
    shared.push_str(&declaration::<SendMessagingResponse>(&cfg));
    shared.push('\n');
    shared.push_str(&declaration::<RuleMatchEntry>(&cfg));
    shared.push('\n');
    shared.push_str(&default_const(
        "DEFAULT_SKILL_NAME",
        "string",
        &crate::model::DEFAULT_SKILL_NAME,
    ));
    shared.push_str(&default_const(
        "DEFAULT_SKILL_PATH",
        "string",
        &crate::model::DEFAULT_SKILL_PATH,
    ));
    shared.push_str(&default_const(
        "DEFAULT_COMMAND_TEMPLATE",
        "string",
        &crate::model::DEFAULT_COMMAND_TEMPLATE,
    ));

    let mut config_types = String::from(HEADER);
    config_types.push_str(
        "import type { ClaudeEffort, CliResolutionSource, CliTool, CodexReasoningEffort, EngineKind, EventType, LabelSource, MessagingProviderKind, NotificationKind, SourceKind, UpdateMode } from \"../types.generated\";\n\n",
    );
    config_types.push_str(&declaration::<WebhookTunnelMode>(&cfg));
    config_types.push_str(&option_array::<WebhookTunnelMode>("WEBHOOK_TUNNEL_MODES"));
    config_types.push('\n');
    config_types.push_str(&declaration::<RemoteCapability>(&cfg));
    config_types.push_str(&option_array::<RemoteCapability>("REMOTE_CAPABILITIES"));
    config_types.push('\n');
    config_types.push_str(&declaration::<SourcePolicyMode>(&cfg));
    config_types.push_str(&option_array::<SourcePolicyMode>("SOURCE_POLICY_MODES"));
    config_types.push('\n');
    config_types.push_str(&declaration::<RemoteTunnelMode>(&cfg));
    config_types.push_str(&option_array::<RemoteTunnelMode>("REMOTE_TUNNEL_MODES"));
    config_types.push('\n');
    config_types.push_str(&declaration::<RemoteEntrypointState>(&cfg));
    config_types.push_str(&option_array::<RemoteEntrypointState>(
        "REMOTE_ENTRYPOINT_STATES",
    ));
    config_types.push('\n');
    config_types.push_str(&declaration::<RemoteTunnelState>(&cfg));
    config_types.push_str(&option_array::<RemoteTunnelState>("REMOTE_TUNNEL_STATES"));
    config_types.push('\n');
    config_types.push_str(&declaration::<OutboxConfig>(&cfg));
    config_types.push('\n');
    config_types.push_str(&declaration::<RuleActionKind>(&cfg));
    config_types.push_str(&option_array::<RuleActionKind>("RULE_ACTION_KINDS"));
    config_types.push('\n');
    config_types.push_str(&declaration::<RuleActionDedupePolicy>(&cfg));
    config_types.push_str(&option_array::<RuleActionDedupePolicy>(
        "RULE_ACTION_DEDUPE_POLICIES",
    ));
    config_types.push('\n');
    config_types.push_str(&declaration::<RuleActionTarget>(&cfg));
    config_types.push('\n');
    config_types.push_str(&declaration::<RuleActionConfig>(&cfg));
    config_types.push('\n');
    config_types.push_str(&declaration::<ReviewLifecycleEvent>(&cfg));
    config_types.push_str(&option_array::<ReviewLifecycleEvent>(
        "REVIEW_LIFECYCLE_EVENTS",
    ));
    config_types.push('\n');
    config_types.push_str(&declaration::<ReviewLifecycleTarget>(&cfg));
    config_types.push('\n');
    config_types.push_str(&declaration::<ReviewLifecycleNotificationConfig>(&cfg));
    config_types.push_str(&default_const(
        "DEFAULT_REVIEW_LIFECYCLE_NOTIFICATION_CONFIG",
        "ReviewLifecycleNotificationConfig",
        &ReviewLifecycleNotificationConfig::default(),
    ));
    config_types.push('\n');
    config_types.push_str(&declaration::<RuleConfig>(&cfg));
    config_types.push('\n');
    config_types.push_str(&declaration::<NotificationChannel>(&cfg));
    config_types.push('\n');
    config_types.push_str(&declaration::<NotificationSettings>(&cfg));
    config_types.push_str(&default_const(
        "DEFAULT_NOTIFICATION_SETTINGS",
        "NotificationSettings",
        &NotificationSettings::default(),
    ));
    config_types.push('\n');
    config_types.push_str(&declaration::<MessagingIntegration>(&cfg));
    config_types.push_str(&default_const(
        "DEFAULT_MESSAGING_INTEGRATION",
        "MessagingIntegration",
        &MessagingIntegration::default(),
    ));
    config_types.push('\n');
    config_types.push_str(&declaration::<MessagingSettings>(&cfg));
    config_types.push_str(&default_const(
        "DEFAULT_MESSAGING_SETTINGS",
        "MessagingSettings",
        &MessagingSettings::default(),
    ));
    config_types.push('\n');
    config_types.push_str(&declaration::<SourcePolicy>(&cfg));
    config_types.push('\n');
    config_types.push_str(&declaration::<RemoteRoute>(&cfg));
    config_types.push('\n');
    config_types.push_str(&declaration::<RemoteEntrypoint>(&cfg));
    config_types.push('\n');
    config_types.push_str(&declaration::<RemoteTunnel>(&cfg));
    config_types.push('\n');
    config_types.push_str(&declaration::<RemoteAccessConfig>(&cfg));
    config_types.push('\n');
    config_types.push_str(&declaration::<CliPath>(&cfg));
    config_types.push('\n');
    config_types.push_str(&declaration::<CliToolsConfig>(&cfg));
    config_types.push_str(&default_const(
        "DEFAULT_CLI_TOOLS_CONFIG",
        "CliToolsConfig",
        &CliToolsConfig::default(),
    ));
    config_types.push('\n');
    config_types.push_str(&declaration::<CliToolProbeStatus>(&cfg));
    config_types.push('\n');
    config_types.push_str(&declaration::<Project>(&cfg));
    config_types.push_str(&default_const(
        "DEFAULT_PROJECT",
        "Project",
        &Project::default(),
    ));
    config_types.push('\n');
    config_types.push_str(&declaration::<AppConfig>(&cfg));
    config_types.push('\n');
    config_types.push_str(&declaration::<RemoteRouteRuntimeStatus>(&cfg));
    config_types.push('\n');
    config_types.push_str(&declaration::<RemoteEntrypointRuntimeStatus>(&cfg));
    config_types.push('\n');
    config_types.push_str(&declaration::<RemoteTunnelRuntimeStatus>(&cfg));
    config_types.push('\n');
    config_types.push_str(&declaration::<RemoteAccessRuntimeStatus>(&cfg));

    vec![
        ("src/types.generated.ts", shared),
        ("src/config/types.generated.ts", config_types),
    ]
}

#[test]
fn generated_config_types_are_current() {
    let repo_root = repo_root();
    for (relative_path, expected) in generated_outputs() {
        let path = repo_root.join(relative_path);
        let actual = fs::read_to_string(&path)
            .unwrap_or_else(|err| panic!("read generated TypeScript {}: {err}", path.display()));
        assert_eq!(
            actual, expected,
            "{} is out of date; run `pnpm run generate:config-types`",
            relative_path
        );
    }
}

#[test]
fn semantic_newtypes_generate_branded_typescript_contracts() {
    let shared = generated_outputs()
        .into_iter()
        .find_map(|(path, contents)| (path == "src/types.generated.ts").then_some(contents))
        .expect("shared TypeScript output exists");

    for (name, primitive) in [
        ("ExternalRequestId", "string"),
        ("InboxDedupeKey", "string"),
        ("ReviewActionKey", "string"),
        ("OutboxProducerKey", "string"),
        ("InboxEventId", "number"),
        ("ReviewReceiptId", "number"),
    ] {
        assert!(
            shared.contains(&format!(
                "export type {name} = Brand<{primitive}, \"{name}\">;"
            )),
            "{name} must remain a distinct branded TypeScript type"
        );
        assert!(
            !shared.contains(&format!("export type {name} = {primitive};")),
            "{name} must not collapse to its primitive TypeScript representation"
        );
    }

    assert!(shared.contains("export function externalRequestId("));
    assert!(shared.contains("export function inboxEventId("));
    assert!(shared.contains("export function reviewReceiptId("));
}

#[test]
fn pull_request_view_is_generated_from_the_rust_wire_type() {
    let shared = generated_outputs()
        .into_iter()
        .find_map(|(path, contents)| (path == "src/types.generated.ts").then_some(contents))
        .expect("shared TypeScript output exists");
    assert!(shared.contains("export type PullRequestView = {"));
    assert!(shared.contains("skillKey: string,"));
    assert!(shared.contains("skipReason: string | null,"));
}

#[test]
#[ignore = "writes generated TypeScript files; run via `pnpm run generate:config-types`"]
fn export_config_types() {
    let repo_root = repo_root();
    for (relative_path, contents) in generated_outputs() {
        write_if_changed(&repo_root.join(relative_path), &contents);
    }
}
