// This file is generated by `pnpm run generate:config-types`. Do not edit.

export type CliTool = "gh" | "az" | "codex" | "claude" | "cloudflared";
export const CLI_TOOLS = ["gh","az","codex","claude","cloudflared"] as const;

export type CliResolutionSource = "custom" | "process-path" | "login-shell-path" | "platform-fallback";
export const CLI_RESOLUTION_SOURCES = ["custom","process-path","login-shell-path","platform-fallback"] as const;

export type SourceKind = "github" | "azure" | "bitbucket";
export const SOURCE_KINDS = ["github","azure","bitbucket"] as const;

export type EngineKind = "codex" | "claude";
export const ENGINE_KINDS = ["codex","claude"] as const;

export type LabelSource = "native" | "title";
export const LABEL_SOURCES = ["native","title"] as const;

export type UpdateMode = "webhook-only" | "pull-only" | "hybrid" | "manual";
export const UPDATE_MODES = ["webhook-only","pull-only","hybrid","manual"] as const;

export type EventType = "pullRequest" | "issue" | "comment" | "label" | "generic";
export const EVENT_TYPES = ["pullRequest","issue","comment","label","generic"] as const;

export type NotificationKind = "desktop" | "email" | "slack" | "telegram" | "weChatWork" | "feishu" | "dingTalk";
export const NOTIFICATION_KINDS = ["desktop","email","slack","telegram","weChatWork","feishu","dingTalk"] as const;

export type MessagingProviderKind = "feishu" | "weChatWork" | "dingTalk";
export const MESSAGING_PROVIDER_KINDS = ["feishu","weChatWork","dingTalk"] as const;

export type MessagingEventStatus = "received" | "processed" | "failed";
export const MESSAGING_EVENT_STATUSES = ["received","processed","failed"] as const;

export type ActionStatus = "pending" | "done" | "dead";
export const ACTION_STATUSES = ["pending","done","dead"] as const;

export type MessagingProviderCapability = { provider: MessagingProviderKind, supportsReply: boolean, supportsSend: boolean, requiresAllowedConversations: boolean, };

export type MessagingIntegrationOption = { id: string, name: string, kind: MessagingProviderKind, allowedConversationIds: Array<string>, };

export type MessagingEvent = { provider: MessagingProviderKind, integrationId: string, eventId: string, conversationId: string, threadId: string, senderId: string, text: string, mentionedBot: boolean, rawPayload: string, receivedAtEpoch: number, };

export type MessagingReplyAudit = { outboxId: number, kind: string, summary: string, status: ActionStatus | null, error: string | null, };

export type MessagingEventEntry = { id: number, event: MessagingEvent, status: MessagingEventStatus, processedAtEpoch: number | null, error: string | null, reply: MessagingReplyAudit | null, };

export type NotificationLevel = "info" | "warning" | "error";
export const NOTIFICATION_LEVELS = ["info","warning","error"] as const;

export type SendNotificationRequest = { level?: NotificationLevel | null, title: string, body?: string | null, url?: string | null, projectId?: string | null, channelIds?: Array<string>, };

export type SendNotificationResponse = { outboxIds: Array<number>, };

export type SendMessagingRequest = { integrationId: string, conversationId: string, text: string, requestId: string, };

export type SendMessagingResponse = { outboxId: number, };

export type RuleMatchEntry = { id: number, ruleId: string, ruleName: string, inboxEventId: number, projectId: string, actionCount: number, error: string | null, createdAt: number, actionOutboxIds: Array<number>, };
