// This file is generated by `pnpm run generate:config-types`. Do not edit.

export type SourceKind = "github" | "azure" | "bitbucket";
export const SOURCE_KINDS = ["github","azure","bitbucket"] as const;

export type EngineKind = "codex" | "claude";
export const ENGINE_KINDS = ["codex","claude"] as const;

export type LabelSource = "native" | "title";
export const LABEL_SOURCES = ["native","title"] as const;

export type UpdateMode = "webhook-only" | "pull-only" | "hybrid" | "manual";
export const UPDATE_MODES = ["webhook-only","pull-only","hybrid","manual"] as const;

export type EventType = "pullRequest" | "issue" | "comment" | "label" | "generic";
export const EVENT_TYPES = ["pullRequest","issue","comment","label","generic"] as const;

export type NotificationKind = "desktop" | "email" | "slack" | "telegram" | "weChatWork" | "feishu" | "dingTalk";
export const NOTIFICATION_KINDS = ["desktop","email","slack","telegram","weChatWork","feishu","dingTalk"] as const;

export type NotificationLevel = "info" | "warning" | "error";
export const NOTIFICATION_LEVELS = ["info","warning","error"] as const;

export type SendNotificationRequest = { level?: NotificationLevel | null, title: string, body?: string | null, url?: string | null, projectId?: string | null, channelIds?: Array<string>, };

export type SendNotificationResponse = { outboxIds: Array<number>, };

export type RuleMatchEntry = { id: number, ruleId: string, ruleName: string, inboxEventId: number, projectId: string, actionCount: number, error: string | null, createdAt: number, actionOutboxIds: Array<number>, };
